// Mocks generated by Mockito 5.4.6 from annotations
// in book_store_app/test/features/home/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:book_store_app/core/data/api_response.dart' as _i2;
import 'package:book_store_app/data/model/book.dart' as _i5;
import 'package:book_store_app/domain/repository/home_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Book>>> getListOfBooks() =>
      (super.noSuchMethod(
            Invocation.method(#getListOfBooks, []),
            returnValue: _i4.Future<_i2.ApiResponse<List<_i5.Book>>>.value(
              _FakeApiResponse_0<List<_i5.Book>>(
                this,
                Invocation.method(#getListOfBooks, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<List<_i5.Book>>>);
}
